# Generated by Django 6.0.6 on 2026-06-10 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=50, verbose_name='Lab ID -S-')),
                ('sample_type', models.CharField(default='BLOOD', max_length=50)),
                ('patient_name', models.CharField(max_length=150)),
                ('receiving_date', models.DateField(default=django.utils.timezone.now)),
                ('reporting_date', models.DateField(default=django.utils.timezone.now)),
                ('age_value', models.IntegerField(default=5)),
                ('age_unit', models.CharField(choices=[('Y', 'Years'), ('M', 'Months'), ('D', 'Days')], default='Y', max_length=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1)),
                ('ref_by', models.CharField(default='NMCH', max_length=150)),
                ('notes', models.TextField(default='This report is not valid for any medico-legal purpose. Result reflect to the sample as received. Interpretation can be done by Clinician. Please contact the Lab for any clarification/re-evalutation of the result.')),
                ('show_prepared_by', models.BooleanField(default=True)),
                ('show_technician', models.BooleanField(default=True)),
                ('show_scientist', models.BooleanField(default=True)),
                ('show_vc', models.BooleanField(default=True)),
                ('prepared_by_name', models.CharField(default='Report Prepared by', max_length=100)),
                ('technician_name', models.CharField(default='Lab Technician / RA', max_length=100)),
                ('scientist_name', models.CharField(default='Research Scientist', max_length=100)),
                ('vc_name', models.CharField(default='Dr. G.C Sahoo', max_length=100)),
                ('vc_title', models.CharField(default='Signature of VC', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(choices=[('HBsAG', 'HBsAG'), ('HCV Antibody', 'HCV Antibody'), ('HVC Antibody', 'HVC Antibody'), ('HAV IgM', 'HAV IgM'), ('Den IgM', 'Den IgM'), ('NS1', 'NS1'), ('hikunugya IgM', 'hikunugya IgM'), ('Leptospira', 'Leptospira'), ('JE Blood', 'JE Blood'), ('JE CSF', 'JE CSF'), ('ST', 'ST'), ('Measles', 'Measles'), ('MUMPS', 'MUMPS'), ('Influenza H1N1', 'Influenza H1N1'), ('Influenza H3N2', 'Influenza H3N2')], max_length=100)),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('interpretation_text', models.CharField(blank=True, max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='reports.report')),
            ],
        ),
    ]
