# Generated by Django 6.0.6 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttest',
            name='test_name',
            field=models.CharField(choices=[('ANTI-HBC IGM', 'ANTI-HBC IGM'), ('ANTI-HBC TOTAL', 'ANTI-HBC TOTAL'), ('ANTI-HBE', 'ANTI-HBE'), ('ANTI-HBS', 'ANTI-HBS'), ('CALICIVIRUS PCR (STOOL)', 'CALICIVIRUS PCR (STOOL)'), ('CHANDIPURA VIRUS RT-PCR', 'CHANDIPURA VIRUS RT-PCR'), ('CHIKUNGUNYA', 'CHIKUNGUNYA'), ('CHIKUNGUNYA IGG', 'CHIKUNGUNYA IGG'), ('CHIKUNGUNYA IGM', 'CHIKUNGUNYA IGM'), ('DENGUE', 'DENGUE'), ('DENGUE IGG', 'DENGUE IGG'), ('DENGUE IGM', 'DENGUE IGM'), ('DENGUE NS1', 'DENGUE NS1'), ('HAV IGG', 'HAV IGG'), ('HAV IGM', 'HAV IGM'), ('HBEAG', 'HBEAG'), ('HBSAG', 'HBSAG'), ('HBV DNA (PCR)', 'HBV DNA (PCR)'), ('HCV ANTIBODY', 'HCV ANTIBODY'), ('HCV RNA (PCR)', 'HCV RNA (PCR)'), ('HEV IGG', 'HEV IGG'), ('HEV IGM', 'HEV IGM'), ('INFLUENZA H1N1', 'INFLUENZA H1N1'), ('INFLUENZA H3N2', 'INFLUENZA H3N2'), ('JE IGM (BLOOD)', 'JE IGM (BLOOD)'), ('JE IGM (CSF)', 'JE IGM (CSF)'), ('LEPTOSPIRA', 'LEPTOSPIRA'), ('LEPTOSPIRA IGM', 'LEPTOSPIRA IGM'), ('LEPTOSPIRA PCR', 'LEPTOSPIRA PCR'), ('MEASLES', 'MEASLES'), ('MEASLES IGG', 'MEASLES IGG'), ('MEASLES IGM', 'MEASLES IGM'), ('MUMPS', 'MUMPS'), ('MUMPS IGG', 'MUMPS IGG'), ('MUMPS IGM', 'MUMPS IGM'), ('SCRUB TYPHUS (ST)', 'SCRUB TYPHUS (ST)'), ('SCRUB TYPHUS IGM', 'SCRUB TYPHUS IGM'), ('VZV IGG', 'VZV IGG'), ('VZV IGM', 'VZV IGM'), ('VZV PCR', 'VZV PCR'), ('ZIKA VIRUS IGM', 'ZIKA VIRUS IGM'), ('ZIKA VIRUS RNA (PCR)', 'ZIKA VIRUS RNA (PCR)')], max_length=100),
        ),
    ]
