# Generated by Django 6.0.6 on 2026-06-18 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reporttest_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='test_method',
            field=models.CharField(blank=True, default='ELISA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='age_unit',
            field=models.CharField(blank=True, choices=[('Y', 'Years'), ('M', 'Months'), ('D', 'Days')], default='Y', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='age_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab ID -S-'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='receiving_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ref_by',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporting_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sample_type',
            field=models.CharField(blank=True, default='BLOOD', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='F', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='reporttest',
            name='interpretation_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporttest',
            name='result_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporttest',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
    ]
