# Generated by Django 4.2.13 on 2026-06-22 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_id_alter_reporttest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Lab ID -S-'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patient_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='receiving_date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ref_by',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150, null=True),
        ),
    ]
