# Generated by Django 4.2.13 on 2026-06-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_created_at_alter_report_lab_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttest',
            name='test_method',
            field=models.CharField(default='ELISA', max_length=50),
        ),
    ]
