# Generated by Django 4.2.13 on 2026-06-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_reporttest_test_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vc_title',
            field=models.CharField(default='Signature of I/C', max_length=100),
        ),
    ]
