# Generated by Django 4.2.13 on 2026-06-29 06:22

from django.db import migrations


def update_signature_titles(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    Report.objects.filter(vc_title='Signature of VC').update(vc_title='Signature of I/C')

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_report_vc_title'),
    ]

    operations = [
        migrations.RunPython(update_signature_titles),
    ]
