# Generated by Django 4.2.13 on 2026-06-29 14:50

from django.db import migrations

def recalculate_interpretation_texts(apps, schema_editor):
    ReportTest = apps.get_model('reports', 'ReportTest')
    
    qualitative_mapping = {
        'positive': 'Positive',
        'negative': 'Negative',
        'equivocal': 'Equivocal',
        'invalid': 'Invalid',
        'reactive': 'Reactive',
        'non-reactive': 'Non-Reactive',
        'nonreactive': 'Non-Reactive'
    }
    
    for test in ReportTest.objects.all():
        method = (test.test_method or '').upper()
        # If result_value is a qualitative string, normalize interpretation_text
        if not test.interpretation_text and test.result_value:
            val_clean = str(test.result_value).strip().lower()
            if val_clean in qualitative_mapping:
                test.interpretation_text = qualitative_mapping[val_clean]
                test.save()
                continue
                
        if method == 'ELISA':
            if test.result_value:
                try:
                    val = float(test.result_value)
                    if test.test_name == 'HBsAg':
                        if val >= 0.191:
                            test.interpretation_text = "Reactive"
                        else:
                            test.interpretation_text = "Non-Reactive"
                    elif test.test_name == 'HCV Antibody':
                        if val >= 0.361:
                            test.interpretation_text = "Reactive"
                        else:
                            test.interpretation_text = "Non-Reactive"
                    else:
                        if val < 9.0:
                            test.interpretation_text = "Negative"
                        elif val > 11.0:
                            test.interpretation_text = "Positive"
                        else:
                            test.interpretation_text = "Equivocal"
                except ValueError:
                    val_clean = str(test.result_value).strip().lower()
                    if val_clean in qualitative_mapping:
                        test.interpretation_text = qualitative_mapping[val_clean]
            test.save()
        else:
            if not test.interpretation_text and test.result_value:
                val_clean = str(test.result_value).strip().lower()
                if val_clean in qualitative_mapping:
                    test.interpretation_text = qualitative_mapping[val_clean]
            test.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20260629_1152'),
    ]

    operations = [
        migrations.RunPython(recalculate_interpretation_texts),
    ]
