# Generated by Django 4.2.13 on 2026-07-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0010_auto_20260629_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(db_index=True, max_length=100)),
                ('test_method', models.CharField(default='ELISA', max_length=100)),
                ('cutoff_value', models.FloatField(blank=True, help_text='e.g. 0.191 or 9.0', null=True)),
                ('cutoff_value_upper', models.FloatField(blank=True, help_text='e.g. 11.0 (optional)', null=True)),
                ('result_type', models.CharField(choices=[('numeric', 'Numeric Range'), ('positive_negative', 'Positive/Negative'), ('select', 'Select (Positive/Negative/Equivocal)')], default='numeric', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_method', 'test_name'],
                'unique_together': {('test_name', 'test_method')},
            },
        ),
    ]
