# Generated by Django 4.2.13 on 2026-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_userprofile_testconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='testconfig',
            name='custom_options',
            field=models.CharField(blank=True, help_text='Comma-separated custom dropdown options (e.g. Option1, Option2, Option3)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testconfig',
            name='result_type',
            field=models.CharField(choices=[('numeric', 'Numeric Range'), ('positive_negative', 'Positive/Negative'), ('select', 'Select (Positive/Negative/Equivocal)'), ('reactive_non_reactive', 'Reactive/Non-Reactive'), ('custom_dropdown', 'Custom Dropdown Choices')], default='numeric', max_length=30),
        ),
    ]
