# Generated by Django 4.2.13 on 2026-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_testconfig_custom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='test_method',
            field=models.CharField(blank=True, db_index=True, default='ELISA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporttest',
            name='test_method',
            field=models.CharField(db_index=True, default='ELISA', max_length=50),
        ),
    ]
