# Generated by Django 4.2.13 on 2026-07-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_report_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
    ]
