# Generated by Django 4.2.13 on 2026-07-23 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_visitor_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporting_date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
